- name: preparing storage
  import_tasks: volumes.yml

- name: Networking
  import_tasks: network.yml

- name: disable the native updater
  import_tasks: disable_updater.yml

- name: Repository issues
  import_tasks: repos.yml

- name: NTP related stuff
  import_tasks: ntp.yml

- name: Software
  import_tasks: software.yml

- name: pull and run external roles out of github
  import_tasks: ext_roles.yml
